url: "https://hp-living-norway.gbif-uat.org"
  
useSharedLibrary: true # Use the new component library
testSite: true #style the site to show that it is a test site
graphqlEndpoint: "https://graphql.gbif-uat.org/graphql" # for use with e.g. new stories from GBIF.org